# Data paths
results_folder: 'none' # if you use local path with checkpoint, please provide the path where it is stored
use_foldseek_sequences: False

# model
esm_checkpoint: 'facebook/esm2_t6_8M_UR50D'
num_struct_embeddings_layers: 1
use_struct_embeddings: True 
mask_angle_inputs_with_plddt: True

predict_contacts: 'none'
batch_limit: 12000

trained_adapter_name: 'DFrolova/MULAN-small' #'mulan_small'

# downstream data
calc_thermostability: True
calc_go: True
calc_metal: True 
calc_humanppi: True
calc_fluorescence: True
calc_ss_pdb: True

downstream_datasets_path: '/workspace/data/docking/downstream_tasks/mulan_datasets'
