# Data paths
results_folder: '/workspace/data/docking/lang_model/data/lora_train_results/'
use_foldseek_sequences: False

# model
esm_checkpoint: 'facebook/esm2_t12_35M_UR50D'
num_struct_embeddings_layers: 1
use_struct_embeddings: True
mask_angle_inputs_with_plddt: True

batch_limit: 12000 
predict_contacts: 'none'

trained_adapter_name: 'mulan_esm2' 

# downstream data
calc_thermostability: True
calc_go: True
calc_metal: True 
calc_humanppi: True
calc_fluorescence: True
calc_ss_pdb: True

downstream_datasets_path: '/workspace/data/docking/downstream_tasks/mulan_datasets'
