# Data paths
results_folder: '/workspace/data/docking/lang_model/data/lora_train_results/'
use_foldseek_sequences: True

# model
esm_checkpoint: 'westlake-repl/SaProt_35M_AF2'
num_struct_embeddings_layers: 1 
use_struct_embeddings: True 
mask_angle_inputs_with_plddt: True

batch_limit: 12000 
predict_contacts: 'none'

trained_adapter_name: 'saprot12_pos_masked_afdb17_1e5_10epoch'

# downstream data
calc_thermostability: True
calc_go: True
calc_metal: True 
calc_humanppi: True
calc_fluorescence: True
calc_ss_pdb: True

downstream_datasets_path: '/workspace/data/docking/downstream_tasks/mulan_datasets'