# provide the correct path where all datasets and computed embeddings are stored
downstream_datasets_path: '/workspace/data/docking/downstream_tasks/mulan_datasets'

downstream_tasks:
  - localization
  - localization_binary
  - thermostability
  - metal
  - humanppi
  - fluorescence
  - go
  - secondary_structure_pdb_3
  - secondary_structure_pdb_8

all_models:
  - DFrolova/MULAN-small
  - DFrolova/MULAN-ESM2-M
  - DFrolova/MULAN-ESM2-L
  # - <your_model_name>